// DBE Annual Teaching Plans — pending sources (URL registered, topics not yet fetched).
// Each entry records that the ATP exists in the DBE registry (DBE Circular S19 of 2025).
// topics: [] and fats: [] until the document is fetched and topic data ingested (OQ-002).
// OQ-005 applies: no source text stored.

import type { ATPSourceDocument } from '../atp-source.js';

export const ATP_PENDING_REGISTRY: readonly ATPSourceDocument[] = [
  {
    sourceId: 'G1-FAL-AF-T1-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 1 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-FAL-AF-T2-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 1 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-FAL-AF-T3-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 1 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-FAL-AF-T4-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 1 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-FAL-EN-T1-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 1 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-FAL-EN-T2-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 1 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-FAL-EN-T3-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 1 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-FAL-EN-T4-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 1 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-HL-AF-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Home Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-HL-EN-T1-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-HL-EN-T2-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-HL-EN-T3-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-HL-EN-T4-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-AF-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-EN-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-XH-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (IsiXhosa) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-ZU-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (IsiZulu) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-SP-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-SS-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (Sesotho) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-TW-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (Setswana) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-SW-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-VD-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G1-LS-TS-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 1 Life Skills (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-FAL-AF-T1-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 2 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-FAL-AF-T2-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 2 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-FAL-AF-T3-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 2 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-FAL-AF-T4-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 2 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-FAL-EN-T1-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 2 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-FAL-EN-T2-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 2 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-FAL-EN-T3-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 2 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-FAL-EN-T4-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 2 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-AF-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-EN-T1-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-EN-T2-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-EN-T3-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-EN-T4-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-IS-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-SE-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-SI-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-TS-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-HL-XI-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Home Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-AF-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-EN-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-XH-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (IsiXhosa) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-ZU-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (IsiZulu) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-SP-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-SS-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (Sesotho) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-TW-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (Setswana) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-SW-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-VD-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G2-LS-TS-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 2 Life Skills (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-HL-EN-T1-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-HL-EN-T2-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-HL-EN-T3-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-HL-EN-T4-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-AF-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-EN-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-XH-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (IsiXhosa) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-ZU-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (IsiZulu) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-SP-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-SS-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (Sesotho) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-TW-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (Setswana) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-SW-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-VD-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G3-LS-TS-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grade 3 Life Skills (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-FAL-AF-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 4 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-FAL-EN-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 4 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-FAL-IS-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 4 First Additional Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-FAL-SE-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 4 First Additional Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-FAL-SI-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 4 First Additional Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-FAL-TS-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 4 First Additional Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-FAL-XI-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 4 First Additional Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-HL-AF-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 4 Home Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-HL-EN-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 4 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-HL-IS-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 4 Home Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-HL-SE-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 4 Home Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-HL-SI-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 4 Home Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-HL-TS-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 4 Home Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G4-HL-XI-2023',
    grade: '4',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 4 Home Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'IP-MULTI-CA-2023',
    grade: '4-6',
    phase: 'Intermediate',
    subject: 'Creative Arts',
    atpYear: 2023,
    sourceDescription: 'Grades 4-6 Creative Arts — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'IP-MULTI-HL-2023',
    grade: '4-6',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grades 4-6 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'IP-MULTI-LS-2023',
    grade: '4-6',
    phase: 'Intermediate',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'Grades 4-6 Life Skills — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'IP-MULTI-MATHS-2023',
    grade: '4-6',
    phase: 'Intermediate',
    subject: 'Mathematics',
    atpYear: 2023,
    sourceDescription: 'Grades 4-6 Mathematics — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'IP-MULTI-NST-2023',
    grade: '4-6',
    phase: 'Intermediate',
    subject: 'Natural Sciences and Technology',
    atpYear: 2023,
    sourceDescription:
      'Grades 4-6 Natural Sciences and Technology — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'IP-MULTI-SS-2023',
    grade: '4-6',
    phase: 'Intermediate',
    subject: 'Social Sciences',
    atpYear: 2023,
    sourceDescription: 'Grades 4-6 Social Sciences — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-FAL-AF-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 5 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-FAL-EN-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 5 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-FAL-IS-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 5 First Additional Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-FAL-SE-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 5 First Additional Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-FAL-SI-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 5 First Additional Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-FAL-TS-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 5 First Additional Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-FAL-XI-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 5 First Additional Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-HL-AF-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 5 Home Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-HL-EN-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 5 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-HL-IS-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 5 Home Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-HL-SE-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 5 Home Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-HL-SI-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 5 Home Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-HL-TS-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 5 Home Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G5-HL-XI-2023',
    grade: '5',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 5 Home Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-FAL-AF-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 6 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-FAL-EN-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 6 First Additional Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-FAL-IS-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 6 First Additional Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-FAL-SE-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 6 First Additional Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-FAL-SI-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 6 First Additional Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-FAL-TS-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 6 First Additional Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-FAL-XI-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 6 First Additional Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-HL-AF-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 6 Home Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-HL-EN-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 6 Home Language (English) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-HL-IS-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 6 Home Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-HL-SE-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 6 Home Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-HL-SI-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 6 Home Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-HL-TS-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 6 Home Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G6-HL-XI-2023',
    grade: '6',
    phase: 'Intermediate',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 6 Home Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-CA-DANCE-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Creative Arts — Dance',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Creative Arts — Dance — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-CA-DRAMA-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Creative Arts — Drama',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Creative Arts — Drama — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-CA-MUSIC-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Creative Arts — Music',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Creative Arts — Music — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-CA-VA-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Creative Arts — Visual Arts',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Creative Arts — Visual Arts — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-FAL-AF-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 7 First Additional Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-FAL-IS-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 7 First Additional Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-FAL-SE-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 7 First Additional Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-FAL-SI-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 7 First Additional Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-FAL-TS-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 7 First Additional Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-FAL-XI-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'Grade 7 First Additional Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-HL-AF-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Home Language (Afrikaans) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-HL-IS-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Home Language (IsiNdebele) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-HL-SE-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Home Language (Sepedi) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-HL-SI-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Home Language (Siswati) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-HL-TS-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Home Language (Tshivenda) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
  {
    sourceId: 'G7-HL-XI-2023',
    grade: '7',
    phase: 'Senior',
    subject: 'Home Language',
    atpYear: 2023,
    sourceDescription: 'Grade 7 Home Language (Xitsonga) — DBE 2023; topics pending',
    topics: [],
    fats: [],
  },
];
