// DBE Annual Teaching Plans — Foundation Phase Gr R–3.
// Derived structure only: topic names, content areas, week ranges, assessment types.
// No source text stored (OQ-005). ratifiedBy is null until a human countersigns.
// Sources: 12 documents · 83 topic blocks · 39 FAT rows.
// Circular S19 of 2025: 2023/24 ATPs remain in force until further notice.

import type { ATPSourceDocument } from '../atp-source.js';
import type { SourceRef } from '../framework.js';

function ref(documentId: string, documentVersion: string, clause: string): SourceRef {
  return { documentId, documentVersion, clause, ratifiedBy: null };
}

export const ATP_FOUNDATION_SOURCES: readonly ATPSourceDocument[] = [
  {
    sourceId: 'GR-FAL-EN-2023',
    grade: 'R',
    phase: 'Foundation',
    subject: 'First Additional Language',
    atpYear: 2023,
    sourceDescription:
      'DBE ATP 2023/24 Grade R English First Additional Language (CAPS-based)',
    topics: [
      {
        sourceId: 'GR-FAL-EN-2023',
        grade: 'R',
        subject: 'First Additional Language',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Listening, Speaking and Oral Language Development',
        topic:
          'GR English FAL T1 — Oral language introduction: greetings, naming, songs/rhymes, classroom vocabulary; phonological awareness foundations',
        assessmentType: 'Informal observation',
        hours: 4.0,
        basis: ref(
          'dbe-atp-gr-fal-en-2023',
          '2023-dbe',
          'Grade R First Additional Language Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-FAL-EN-2023',
        grade: 'R',
        subject: 'First Additional Language',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Listening, Speaking and Oral Language Development',
        topic:
          'GR English FAL T2 — Oral language: storytelling/descriptions, expanded vocabulary (community), phonological awareness; simple rhymes/songs',
        assessmentType: 'Informal observation',
        hours: 4.0,
        basis: ref(
          'dbe-atp-gr-fal-en-2023',
          '2023-dbe',
          'Grade R First Additional Language Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-FAL-EN-2023',
        grade: 'R',
        subject: 'First Additional Language',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Listening, Speaking and Oral Language Development',
        topic:
          'GR English FAL T3 — Oral language: retelling stories/sequencing, expanded vocabulary (nature/science), phonological awareness (initial sounds/rhyme), pre-reading (shared books)',
        assessmentType: 'Informal observation',
        hours: 4.0,
        basis: ref(
          'dbe-atp-gr-fal-en-2023',
          '2023-dbe',
          'Grade R First Additional Language Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-FAL-EN-2023',
        grade: 'R',
        subject: 'First Additional Language',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Listening, Speaking and Oral Language Development',
        topic:
          'GR English FAL T4 — Oral language consolidation: conversations/presentations, rich vocabulary, phonological awareness consolidation, preparing for Grade 1 English FAL',
        assessmentType: 'Informal observation + end-of-year record',
        hours: 4.0,
        basis: ref(
          'dbe-atp-gr-fal-en-2023',
          '2023-dbe',
          'Grade R First Additional Language Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'GR-FAL-EN-2023',
        grade: 'R',
        subject: 'First Additional Language',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'End-of-year observation record',
        fatDescription:
          'End-of-year observation record and Grade 1 readiness assessment. All assessment in Grade R is informal, continuous and observational (T1-T4).',
        weekNumber: 9,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'End-of-year',
        basis: ref(
          'dbe-atp-gr-fal-en-2023',
          '2023-dbe',
          'Grade R First Additional Language FAT Term 4',
        ),
      },
    ],
  },
  {
    sourceId: 'GR-LS-EN-2023',
    grade: 'R',
    phase: 'Foundation',
    subject: 'Life Skills',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade R Life Skills (CAPS-based)',
    topics: [
      {
        sourceId: 'GR-LS-EN-2023',
        grade: 'R',
        subject: 'Life Skills',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea:
          'Life Skills — Beginning Knowledge, Creative Arts, Physical Education',
        topic:
          'GR Life Skills T1 — Beginning Knowledge (self/family/home), Creative Arts (play/music/visual art intro), Physical Education (gross/fine motor)',
        assessmentType: 'Informal observation',
        hours: 9.0,
        basis: ref(
          'dbe-atp-gr-ls-en-2023',
          '2023-dbe',
          'Grade R Life Skills Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-LS-EN-2023',
        grade: 'R',
        subject: 'Life Skills',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea:
          'Life Skills — Beginning Knowledge, Creative Arts, Physical Education',
        topic:
          'GR Life Skills T2 — Beginning Knowledge (community/environment/weather), Creative Arts (music/art/drama), Physical Education (movement sequences/games)',
        assessmentType: 'Informal observation',
        hours: 9.0,
        basis: ref(
          'dbe-atp-gr-ls-en-2023',
          '2023-dbe',
          'Grade R Life Skills Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-LS-EN-2023',
        grade: 'R',
        subject: 'Life Skills',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea:
          'Life Skills — Beginning Knowledge, Creative Arts, Physical Education',
        topic:
          'GR Life Skills T3 — Beginning Knowledge (plants/animals/environment deeper), Creative Arts (cultural arts/drama), Physical Education (rhythmic movement/games)',
        assessmentType: 'Informal observation',
        hours: 9.0,
        basis: ref(
          'dbe-atp-gr-ls-en-2023',
          '2023-dbe',
          'Grade R Life Skills Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-LS-EN-2023',
        grade: 'R',
        subject: 'Life Skills',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea:
          'Life Skills — Beginning Knowledge, Creative Arts, Physical Education',
        topic:
          'GR Life Skills T4 — Beginning Knowledge (transport/technology/science concepts), Creative Arts (integrated performance), Physical Education (sport/games/movement skills)',
        assessmentType: 'Informal observation + end-of-year record',
        hours: 9.0,
        basis: ref(
          'dbe-atp-gr-ls-en-2023',
          '2023-dbe',
          'Grade R Life Skills Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'GR-LS-EN-2023',
        grade: 'R',
        subject: 'Life Skills',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'End-of-year observation record',
        fatDescription:
          'End-of-year observation record and progression decision. All assessment in Grade R Life Skills is informal, continuous and observational (T1-T4). Observation of learner progress in all three strands: Beginning Knowledge (PSWB), Creative Arts, and Physical Education.',
        weekNumber: 9,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'End-of-year',
        basis: ref('dbe-atp-gr-ls-en-2023', '2023-dbe', 'Grade R Life Skills FAT Term 4'),
      },
    ],
  },
  {
    sourceId: 'GR-MATHS-2023',
    grade: 'R',
    phase: 'Foundation',
    subject: 'Mathematics',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade R Mathematics (CAPS-based)',
    topics: [
      {
        sourceId: 'GR-MATHS-2023',
        grade: 'R',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic:
          'GR Maths T1 — Number range 1-5: counting, one-to-one correspondence, compare collections, oral problem-solving; Geometric patterns; 3D objects, 2D shapes, position; Time; Data Handling',
        assessmentType: 'Informal observation',
        hours: 7.0,
        basis: ref(
          'dbe-atp-gr-maths-2023',
          '2023-dbe',
          'Grade R Mathematics Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-MATHS-2023',
        grade: 'R',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic:
          'GR Maths T2 — Number range 1-7: counting/one-to-one/compare; Geometric patterns; 3D objects, 2D shapes; Time; Mass; Data Handling',
        assessmentType: 'Informal observation',
        hours: 7.0,
        basis: ref(
          'dbe-atp-gr-maths-2023',
          '2023-dbe',
          'Grade R Mathematics Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-MATHS-2023',
        grade: 'R',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic:
          'GR Maths T3 — Number range 1-9: counting/compare/oral problems; Geometric patterns; Space & Shape; Time; Length; Data Handling',
        assessmentType: 'Informal observation',
        hours: 7.0,
        basis: ref(
          'dbe-atp-gr-maths-2023',
          '2023-dbe',
          'Grade R Mathematics Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'GR-MATHS-2023',
        grade: 'R',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic:
          'GR Maths T4 — Number range 1-10: counting/symbols/names/compare/oral problems; Geometric patterns; Space & Shape; Time; Capacity/Volume; Data Handling',
        assessmentType: 'Informal observation + end-of-year record',
        hours: 7.0,
        basis: ref(
          'dbe-atp-gr-maths-2023',
          '2023-dbe',
          'Grade R Mathematics Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'GR-MATHS-2023',
        grade: 'R',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'End-of-year observation record',
        fatDescription:
          'End-of-year observation record and progression meeting. Determines whether learner is ready for Grade 1. All assessment in Grade R is informal, continuous and observational (T1-T4). Final recording of observations and progression decision at end of T4.',
        weekNumber: 9,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'End-of-year',
        basis: ref('dbe-atp-gr-maths-2023', '2023-dbe', 'Grade R Mathematics FAT Term 4'),
      },
    ],
  },
  {
    sourceId: 'G1-FAL-EN-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'English First Additional Language',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 1 English First Additional Language',
    topics: [
      {
        sourceId: 'G1-FAL-EN-2023',
        grade: '1',
        subject: 'English First Additional Language',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Listening, Speaking, Reading and Phonics',
        topic:
          'G1 EFAL T1 — Listening/Speaking (songs/rhymes/routines), Phonics (letter sounds A-M), Reading (big books/word cards), Writing (drawing/letters/words)',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g1-fal-en-2023',
          '2023-dbe',
          'Grade 1 English First Additional Language Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-FAL-EN-2023',
        grade: '1',
        subject: 'English First Additional Language',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Listening, Speaking, Reading and Phonics',
        topic:
          'G1 EFAL T2 — Listening/Speaking (stories/descriptions), Phonics (letter sounds N-Z), Reading (big books/sentences/sight words), Writing (copying sentences/labels)',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g1-fal-en-2023',
          '2023-dbe',
          'Grade 1 English First Additional Language Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-FAL-EN-2023',
        grade: '1',
        subject: 'English First Additional Language',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Reading, Writing and Language',
        topic:
          'G1 EFAL T3 — Listening/Speaking (stories/retellings), Phonics (blending/segmenting/word families), Reading (sentences/sight words/comprehension), Writing (simple sentences)',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g1-fal-en-2023',
          '2023-dbe',
          'Grade 1 English First Additional Language Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-FAL-EN-2023',
        grade: '1',
        subject: 'English First Additional Language',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Reading, Writing and Language',
        topic:
          'G1 EFAL T4 — Listening/Speaking (conversations/presentations), Phonics (word families/digraphs), Reading (simple texts/comprehension), Writing (3+ sentences/descriptions)',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g1-fal-en-2023',
          '2023-dbe',
          'Grade 1 English First Additional Language Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G1-FAL-EN-2023',
        grade: '1',
        subject: 'English First Additional Language',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (L&S: retelling/descriptions) + Practical (Reading: comprehension) + Written (3-5 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g1-fal-en-2023',
          '2023-dbe',
          'Grade 1 English First Additional Language FAT Term 1',
        ),
      },
      {
        sourceId: 'G1-FAL-EN-2023',
        grade: '1',
        subject: 'English First Additional Language',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (discussion/story retelling) + Written (Creative or transactional 5-8 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g1-fal-en-2023',
          '2023-dbe',
          'Grade 1 English First Additional Language FAT Term 2',
        ),
      },
      {
        sourceId: 'G1-FAL-EN-2023',
        grade: '1',
        subject: 'English First Additional Language',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation/interview) + Written (Report or transactional 5-10 sentences); OR Project Stages 1+2',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g1-fal-en-2023',
          '2023-dbe',
          'Grade 1 English First Additional Language FAT Term 3',
        ),
      },
      {
        sourceId: 'G1-FAL-EN-2023',
        grade: '1',
        subject: 'English First Additional Language',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation or poetry) + Written (Creative or transactional 8-12 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g1-fal-en-2023',
          '2023-dbe',
          'Grade 1 English First Additional Language FAT Term 4',
        ),
      },
    ],
  },
  {
    sourceId: 'G1-HL-EN-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'English Home Language',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 1 English Home Language',
    topics: [
      {
        sourceId: 'G1-HL-EN-2023',
        grade: '1',
        subject: 'English Home Language',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G1 EHL T1 — Listening/Speaking, Phonics (single letters/CVC words), Shared/GGR Reading (big books), Writing (news/3 sentences), Handwriting (lower case formation)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g1-hl-en-2023',
          '2023-dbe',
          'Grade 1 English Home Language Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-HL-EN-2023',
        grade: '1',
        subject: 'English Home Language',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G1 EHL T2 — Listening/Speaking (stories), Phonics (blends/digraphs ch/th), Reading (comprehension), Writing (3+ sentences/creative), Handwriting (lower/upper case)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g1-hl-en-2023',
          '2023-dbe',
          'Grade 1 English Home Language Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-HL-EN-2023',
        grade: '1',
        subject: 'English Home Language',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G1 EHL T3 — Listening/Speaking (poems/songs), Phonics (long vowels/blends), Reading (comprehension/fluency), Writing (creative stories/poems), Handwriting (joined letters intro)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g1-hl-en-2023',
          '2023-dbe',
          'Grade 1 English Home Language Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-HL-EN-2023',
        grade: '1',
        subject: 'English Home Language',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G1 EHL T4 — Listening/Speaking (conversations), Phonics (consolidation/vowel digraphs), Reading (fluency/comprehension), Writing (transactional/creative), Handwriting (consolidation)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g1-hl-en-2023',
          '2023-dbe',
          'Grade 1 English Home Language Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G1-HL-EN-2023',
        grade: '1',
        subject: 'English Home Language',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (L&S) + Practical (GGR Reading) + Written (News/story 3+ sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g1-hl-en-2023',
          '2023-dbe',
          'Grade 1 English Home Language FAT Term 1',
        ),
      },
      {
        sourceId: 'G1-HL-EN-2023',
        grade: '1',
        subject: 'English Home Language',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (story retelling) + Written (Creative story/letter with paragraphs)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g1-hl-en-2023',
          '2023-dbe',
          'Grade 1 English Home Language FAT Term 2',
        ),
      },
      {
        sourceId: 'G1-HL-EN-2023',
        grade: '1',
        subject: 'English Home Language',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (read aloud/presentation) + Written (Creative or transactional writing)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g1-hl-en-2023',
          '2023-dbe',
          'Grade 1 English Home Language FAT Term 3',
        ),
      },
      {
        sourceId: 'G1-HL-EN-2023',
        grade: '1',
        subject: 'English Home Language',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation/poetry) + Written (Creative or transactional, 5-10+ sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g1-hl-en-2023',
          '2023-dbe',
          'Grade 1 English Home Language FAT Term 4',
        ),
      },
    ],
  },
  {
    sourceId: 'G1-MATHS-2023',
    grade: '1',
    phase: 'Foundation',
    subject: 'Mathematics',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 1 Mathematics',
    topics: [
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T1 W1–2 (Readiness)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 1 Week 1–2',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Time and Length T1',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape and Patterns T1',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T1 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 1 Week 3–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T2 W1–2 (Diagnostic)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 2 Week 1–2',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Time and Length T2',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape, Patterns and Data T2',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T2 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 2 Week 3–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T3 W1–2 (Diagnostic 2)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 3 Week 1–2',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T3',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape, Patterns and Data T3',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T3 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 3 Week 3–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T4 W1–2 (End-line)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 4 Week 1–2',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T4',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 4 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape and Patterns T4',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 4 Week 1–10',
        ),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T4 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g1-maths-2023',
          '2023-dbe',
          'Grade 1 Mathematics Term 4 Week 3–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g1-maths-2023', '2023-dbe', 'Grade 1 Mathematics FAT Term 1'),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g1-maths-2023', '2023-dbe', 'Grade 1 Mathematics FAT Term 2'),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g1-maths-2023', '2023-dbe', 'Grade 1 Mathematics FAT Term 3'),
      },
      {
        sourceId: 'G1-MATHS-2023',
        grade: '1',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g1-maths-2023', '2023-dbe', 'Grade 1 Mathematics FAT Term 4'),
      },
    ],
  },
  {
    sourceId: 'G2-FAL-EN-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'English First Additional Language',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 2 English First Additional Language',
    topics: [
      {
        sourceId: 'G2-FAL-EN-2023',
        grade: '2',
        subject: 'English First Additional Language',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All FAL Skills',
        topic:
          'G2 EFAL T1 — Listening/Speaking (stories/instructions), Phonics (revise/word families/digraphs), Reading (simple readers/comprehension), Writing (3-5 sentences/news)',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g2-fal-en-2023',
          '2023-dbe',
          'Grade 2 English First Additional Language Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-FAL-EN-2023',
        grade: '2',
        subject: 'English First Additional Language',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All FAL Skills',
        topic:
          'G2 EFAL T2 — Listening/Speaking (discussions/drama), Phonics (long vowels/blends), Reading (texts/comprehension/fluency), Writing (creative/transactional 5-7 sentences)',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g2-fal-en-2023',
          '2023-dbe',
          'Grade 2 English First Additional Language Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-FAL-EN-2023',
        grade: '2',
        subject: 'English First Additional Language',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All FAL Skills',
        topic:
          'G2 EFAL T3 — Listening/Speaking (presentations/interviews), Phonics (diphthongs/multi-syllable), Reading (fluency/comprehension/text types), Writing (5-8 sentences/report/transactional)',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g2-fal-en-2023',
          '2023-dbe',
          'Grade 2 English First Additional Language Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-FAL-EN-2023',
        grade: '2',
        subject: 'English First Additional Language',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All FAL Skills',
        topic:
          'G2 EFAL T4 — Listening/Speaking (debates/oral), Phonics (consolidation/fluency), Reading (extended/independent/comprehension), Writing (8-10 sentences/creative/transactional)',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g2-fal-en-2023',
          '2023-dbe',
          'Grade 2 English First Additional Language Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G2-FAL-EN-2023',
        grade: '2',
        subject: 'English First Additional Language',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (L&S: retelling/descriptions) + Practical (Reading: comprehension) + Written (3-5 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g2-fal-en-2023',
          '2023-dbe',
          'Grade 2 English First Additional Language FAT Term 1',
        ),
      },
      {
        sourceId: 'G2-FAL-EN-2023',
        grade: '2',
        subject: 'English First Additional Language',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (discussion/story retelling) + Written (Creative or transactional 5-8 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g2-fal-en-2023',
          '2023-dbe',
          'Grade 2 English First Additional Language FAT Term 2',
        ),
      },
      {
        sourceId: 'G2-FAL-EN-2023',
        grade: '2',
        subject: 'English First Additional Language',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation/interview) + Written (Report or transactional 5-10 sentences); OR Project Stages 1+2',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g2-fal-en-2023',
          '2023-dbe',
          'Grade 2 English First Additional Language FAT Term 3',
        ),
      },
      {
        sourceId: 'G2-FAL-EN-2023',
        grade: '2',
        subject: 'English First Additional Language',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation or poetry) + Written (Creative or transactional 8-12 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g2-fal-en-2023',
          '2023-dbe',
          'Grade 2 English First Additional Language FAT Term 4',
        ),
      },
    ],
  },
  {
    sourceId: 'G2-HL-EN-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'English Home Language',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 2 English Home Language',
    topics: [
      {
        sourceId: 'G2-HL-EN-2023',
        grade: '2',
        subject: 'English Home Language',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G2 EHL T1 — L&S (news/stories), Phonics (revise G1/short vowels/digraphs/blends), Reading (shared big books/GGR fluency), Writing (3+ sentences/class story), Handwriting (upper/lower case)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g2-hl-en-2023',
          '2023-dbe',
          'Grade 2 English Home Language Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-HL-EN-2023',
        grade: '2',
        subject: 'English Home Language',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G2 EHL T2 — L&S (discussions/stories), Phonics (long vowels/vowel digraphs), Reading (comprehension/figurative language), Writing (creative/transactional), Handwriting (joined letters intro)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g2-hl-en-2023',
          '2023-dbe',
          'Grade 2 English Home Language Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-HL-EN-2023',
        grade: '2',
        subject: 'English Home Language',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G2 EHL T3 — L&S (instructions/retelling), Phonics (diphthongs/multi-syllable), Reading (comprehension strategies/fluency), Writing (transactional/creative), Handwriting (joined letters)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g2-hl-en-2023',
          '2023-dbe',
          'Grade 2 English Home Language Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-HL-EN-2023',
        grade: '2',
        subject: 'English Home Language',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G2 EHL T4 — L&S (conversations/oral presentations), Phonics (consolidation/silent letters), Reading (fluency/comprehension/critical), Writing (creative/transactional/report), Handwriting (joined/legible)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g2-hl-en-2023',
          '2023-dbe',
          'Grade 2 English Home Language Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G2-HL-EN-2023',
        grade: '2',
        subject: 'English Home Language',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (L&S) + Practical (GGR Reading) + Written (News/story 3+ sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g2-hl-en-2023',
          '2023-dbe',
          'Grade 2 English Home Language FAT Term 1',
        ),
      },
      {
        sourceId: 'G2-HL-EN-2023',
        grade: '2',
        subject: 'English Home Language',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (story retelling) + Written (Creative story/letter with paragraphs)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g2-hl-en-2023',
          '2023-dbe',
          'Grade 2 English Home Language FAT Term 2',
        ),
      },
      {
        sourceId: 'G2-HL-EN-2023',
        grade: '2',
        subject: 'English Home Language',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (read aloud/presentation) + Written (Creative or transactional writing)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g2-hl-en-2023',
          '2023-dbe',
          'Grade 2 English Home Language FAT Term 3',
        ),
      },
      {
        sourceId: 'G2-HL-EN-2023',
        grade: '2',
        subject: 'English Home Language',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation/poetry) + Written (Creative or transactional, 5-10+ sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g2-hl-en-2023',
          '2023-dbe',
          'Grade 2 English Home Language FAT Term 4',
        ),
      },
    ],
  },
  {
    sourceId: 'G2-MATHS-2023',
    grade: '2',
    phase: 'Foundation',
    subject: 'Mathematics',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 2 Mathematics',
    topics: [
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T1 W1–2 (Baseline)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 1 Week 1–2',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T1',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape, Patterns and Data T1',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T1 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 1 Week 3–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T2 W1–2 (Diagnostic)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 2 Week 1–2',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T2',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T2 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 2 Week 3–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T3 W1–2 (Diagnostic 2)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 3 Week 1–2',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T3',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape, Patterns and Data T3',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T3 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 3 Week 3–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T4 W1–2 (End-line)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 4 Week 1–2',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T4',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 4 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape, Patterns and Data T4',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 4 Week 1–10',
        ),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T4 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g2-maths-2023',
          '2023-dbe',
          'Grade 2 Mathematics Term 4 Week 3–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g2-maths-2023', '2023-dbe', 'Grade 2 Mathematics FAT Term 1'),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g2-maths-2023', '2023-dbe', 'Grade 2 Mathematics FAT Term 2'),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g2-maths-2023', '2023-dbe', 'Grade 2 Mathematics FAT Term 3'),
      },
      {
        sourceId: 'G2-MATHS-2023',
        grade: '2',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g2-maths-2023', '2023-dbe', 'Grade 2 Mathematics FAT Term 4'),
      },
    ],
  },
  {
    sourceId: 'G3-FAL-EN-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'English First Additional Language',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 3 English First Additional Language',
    topics: [
      {
        sourceId: 'G3-FAL-EN-2023',
        grade: '3',
        subject: 'English First Additional Language',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All FAL Skills',
        topic:
          'G3 EFAL T1 — Listening/Speaking (discussions/retelling), Reading (texts/comprehension/fluency), Writing (creative/transactional 8-10 sentences), Language conventions',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g3-fal-en-2023',
          '2023-dbe',
          'Grade 3 English First Additional Language Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-FAL-EN-2023',
        grade: '3',
        subject: 'English First Additional Language',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All FAL Skills',
        topic:
          'G3 EFAL T2 — Listening/Speaking (debates/presentations), Reading (literary/informational/visual texts), Writing (research/informational/transactional 10-12 sentences), Language conventions',
        assessmentType: 'Oral/practical/written',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g3-fal-en-2023',
          '2023-dbe',
          'Grade 3 English First Additional Language Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-FAL-EN-2023',
        grade: '3',
        subject: 'English First Additional Language',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All FAL Skills',
        topic:
          'G3 EFAL T3 — Listening/Speaking (interviews/research discussions), Reading (drama/folk tale/informational), Writing (creative writing project/research stages), Language conventions',
        assessmentType: 'Project (Research + Writing)',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g3-fal-en-2023',
          '2023-dbe',
          'Grade 3 English First Additional Language Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-FAL-EN-2023',
        grade: '3',
        subject: 'English First Additional Language',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All FAL Skills',
        topic:
          'G3 EFAL T4 — Listening/Speaking (oral project presentation), Reading (revision/extended/independent), Writing (transactional/creative consolidation), Language conventions (revision)',
        assessmentType: 'Oral presentation',
        hours: 4.0,
        basis: ref(
          'dbe-atp-g3-fal-en-2023',
          '2023-dbe',
          'Grade 3 English First Additional Language Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G3-FAL-EN-2023',
        grade: '3',
        subject: 'English First Additional Language',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (L&S: retelling/descriptions) + Practical (Reading: comprehension) + Written (3-5 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g3-fal-en-2023',
          '2023-dbe',
          'Grade 3 English First Additional Language FAT Term 1',
        ),
      },
      {
        sourceId: 'G3-FAL-EN-2023',
        grade: '3',
        subject: 'English First Additional Language',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (discussion/story retelling) + Written (Creative or transactional 5-8 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g3-fal-en-2023',
          '2023-dbe',
          'Grade 3 English First Additional Language FAT Term 2',
        ),
      },
      {
        sourceId: 'G3-FAL-EN-2023',
        grade: '3',
        subject: 'English First Additional Language',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation/interview) + Written (Report or transactional 5-10 sentences); OR Project Stages 1+2',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g3-fal-en-2023',
          '2023-dbe',
          'Grade 3 English First Additional Language FAT Term 3',
        ),
      },
      {
        sourceId: 'G3-FAL-EN-2023',
        grade: '3',
        subject: 'English First Additional Language',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation or poetry) + Written (Creative or transactional 8-12 sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g3-fal-en-2023',
          '2023-dbe',
          'Grade 3 English First Additional Language FAT Term 4',
        ),
      },
    ],
  },
  {
    sourceId: 'G3-HL-EN-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'English Home Language',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 3 English Home Language',
    topics: [
      {
        sourceId: 'G3-HL-EN-2023',
        grade: '3',
        subject: 'English Home Language',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G3 EHL T1 — L&S (discussions/oral presentations), Phonics (revise G2/silent letters/prefixes/suffixes), Reading (process/comprehension/fluency), Writing (creative/transactional), Handwriting (joined script)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g3-hl-en-2023',
          '2023-dbe',
          'Grade 3 English Home Language Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-HL-EN-2023',
        grade: '3',
        subject: 'English Home Language',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G3 EHL T2 — L&S (debates/panel discussions), Phonics (complex patterns/etymology), Reading (literary/informational texts), Writing (narrative/transactional), Handwriting (consolidation)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g3-hl-en-2023',
          '2023-dbe',
          'Grade 3 English Home Language Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-HL-EN-2023',
        grade: '3',
        subject: 'English Home Language',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G3 EHL T3 — L&S (interviews/research discussions), Phonics (fluency/complex words), Reading (comprehension/literary/research), Writing (creative/informational/research), Handwriting (legible/neat)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g3-hl-en-2023',
          '2023-dbe',
          'Grade 3 English Home Language Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-HL-EN-2023',
        grade: '3',
        subject: 'English Home Language',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'All skills',
        topic:
          'G3 EHL T4 — L&S (oral presentations/poetry/drama), Phonics (consolidation/fluency), Reading (extended/independent), Writing (creative/transactional/poetry), Handwriting (fluent/legible)',
        assessmentType: 'Oral/practical/written',
        hours: 7.0,
        basis: ref(
          'dbe-atp-g3-hl-en-2023',
          '2023-dbe',
          'Grade 3 English Home Language Term 4 Week 1–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G3-HL-EN-2023',
        grade: '3',
        subject: 'English Home Language',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (L&S) + Practical (GGR Reading) + Written (News/story 3+ sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g3-hl-en-2023',
          '2023-dbe',
          'Grade 3 English Home Language FAT Term 1',
        ),
      },
      {
        sourceId: 'G3-HL-EN-2023',
        grade: '3',
        subject: 'English Home Language',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (story retelling) + Written (Creative story/letter with paragraphs)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g3-hl-en-2023',
          '2023-dbe',
          'Grade 3 English Home Language FAT Term 2',
        ),
      },
      {
        sourceId: 'G3-HL-EN-2023',
        grade: '3',
        subject: 'English Home Language',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (read aloud/presentation) + Written (Creative or transactional writing)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g3-hl-en-2023',
          '2023-dbe',
          'Grade 3 English Home Language FAT Term 3',
        ),
      },
      {
        sourceId: 'G3-HL-EN-2023',
        grade: '3',
        subject: 'English Home Language',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated SBA (oral/practical/written)',
        fatDescription:
          'Oral (presentation/poetry) + Written (Creative or transactional, 5-10+ sentences)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref(
          'dbe-atp-g3-hl-en-2023',
          '2023-dbe',
          'Grade 3 English Home Language FAT Term 4',
        ),
      },
    ],
  },
  {
    sourceId: 'G3-MATHS-2023',
    grade: '3',
    phase: 'Foundation',
    subject: 'Mathematics',
    atpYear: 2023,
    sourceDescription: 'DBE ATP 2023/24 Grade 3 Mathematics',
    topics: [
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T1 W1–2 (Baseline)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 1 Week 1–2',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T1',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape, Patterns and Data T1',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 1 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T1 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 1 Week 3–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T2 W1–2 (Diagnostic)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 2 Week 1–2',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T2',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape, Patterns and Data T2',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 2 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T2 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 2 Week 3–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T3 W1–2 (Diagnostic 2)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 3 Week 1–2',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T3',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape, Patterns and Data T3',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 3 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T3 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 3 Week 3–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 2,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T4 W1–2 (End-line)',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 4 Week 1–2',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Measurement',
        topic: 'Measurement T4',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 4 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 1,
        weekEnd: 10,
        contentArea: 'Space and Shape',
        topic: 'Space, Shape and Patterns T4',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 4 Week 1–10',
        ),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        weekStart: 3,
        weekEnd: 10,
        contentArea: 'Numbers, Operations and Relationships',
        topic: 'Number Concept Development T4 W3–10',
        assessmentType: null,
        hours: null,
        basis: ref(
          'dbe-atp-g3-maths-2023',
          '2023-dbe',
          'Grade 3 Mathematics Term 4 Week 3–10',
        ),
      },
    ],
    fats: [
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 1 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g3-maths-2023', '2023-dbe', 'Grade 3 Mathematics FAT Term 1'),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 2 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g3-maths-2023', '2023-dbe', 'Grade 3 Mathematics FAT Term 2'),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 3 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g3-maths-2023', '2023-dbe', 'Grade 3 Mathematics FAT Term 3'),
      },
      {
        sourceId: 'G3-MATHS-2023',
        grade: '3',
        subject: 'Mathematics',
        term: 4 as 1 | 2 | 3 | 4,
        fatNumber: 1,
        fatType: 'Integrated (oral/practical/written)',
        fatDescription:
          '1 FAT per term: integrated oral, practical and written assessment across all content areas (NOR, Measurement, Space & Shape, Patterns, Data Handling)',
        weekNumber: null,
        durationHours: null,
        markTotal: null,
        sbaContribution: 'SBA',
        basis: ref('dbe-atp-g3-maths-2023', '2023-dbe', 'Grade 3 Mathematics FAT Term 4'),
      },
    ],
  },
];
