version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html # your app directory on EC2
hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
