version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18 # change to your runtime (python, java, etc.)
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build # your build output folder
