// @infinite-ai/contracts — Zod schemas shared by the API, agents and UI. Three families
// live here: the POPIA vocabularies (purpose taxonomy, consent ledger, retention schedule),
// the curriculum framework, and the Model Gateway's OpenAI-compatible wire contract.
//
// These are contracts rather than implementations on purpose. `packages/policy` decides,
// `packages/db` stores and the modules consume — and all three agree because each agrees
// with this package, rather than with one another.

export {
  DataCategory,
  PURPOSES,
  Purpose,
  definitionOf,
  permits,
  projectCategories,
  type CategoryProjection,
  type PurposeDefinition,
} from './popia/purpose.js';

export {
  ConsentDecision,
  ConsentEntry,
  ConsentEntryDraft,
  ConsentSource,
  LawfulBasis,
  WITHDRAWABLE_BASES,
  isWithdrawable,
} from './popia/consent.js';

export {
  RetentionAnchor,
  RetentionRule,
  RetentionSchedule,
  addMonths,
  evaluateRetention,
  reviewSchedule,
  ruleFor,
  unscheduledCategories,
  type RetainableRecord,
  type RetentionVerdict,
  type ScheduleFinding,
  type ScheduleReview,
} from './popia/retention.js';

export {
  AssessmentWeighting,
  CurriculumFramework,
  FrameworkNeedsInput,
  FrameworkResult,
  GradeFramework,
  GradeLabel,
  Phase,
  SourceRef,
  Sourced,
  SubjectFramework,
  TimeAllocation,
} from './curriculum/framework.js';

export {
  ArtefactType,
  TemplateDefinition,
  TemplateField,
  TemplateSection,
  checkArtefactStructure,
  type ArtefactStructure,
  type TemplateFidelityViolation,
} from './curriculum/template.js';

export {
  ATPNeedsInput,
  ATPResult,
  ATPSchedule,
  ATPTopicEntry,
  ATPWeek,
  CE01Input,
  CE02Input,
  SchoolCalendarBlock,
  WeekKind,
} from './curriculum/atp.js';

export {
  CE03Input,
  CE04Input,
  CognitiveLevel,
  EvidenceItem,
  SuccessCriterion,
  TermAssessmentTask,
  TermPlan,
  TermPlanNeedsInput,
  TermPlanResult,
  TermPlanSubject,
  TermPlanWeekEntry,
  UnitBlueprint,
  UnitBlueprintResult,
  UnitNeedsInput,
} from './curriculum/planning.js';

export {
  ActivityKind,
  CE05Input,
  CE08Input,
  DifferentiatedSet,
  DifferentiatedTier,
  DifferentiationNeedsInput,
  DifferentiationResult,
  DifferentiationTierName,
  Lesson,
  LessonActivity,
  LessonPlan,
  LessonPlanNeedsInput,
  LessonPlanResult,
} from './curriculum/lesson.js';

export {
  AssessmentDesignNeedsInput,
  AssessmentQuestion,
  AssessmentSection,
  AssessmentTaskDesign,
  AssessmentTaskDesignResult,
  AssessmentTaskKind,
  CE06Input,
  CE07Input,
  CognitiveLevelSpread,
  Rubric,
  RubricCriterion,
  RubricDescriptors,
  RubricNeedsInput,
  RubricResult,
} from './curriculum/assessment.js';

export {
  CE09Input,
  CoverageAudit,
  CoverageAuditNeedsInput,
  CoverageAuditResult,
  DriftItem,
  DriftKind,
} from './curriculum/coverage.js';

export {
  BINARY_FORMATS,
  ExportFormat,
  ExportJob,
  ExportJobStatus,
  ExportRequest,
  ExportResult,
  PUBLICATION_CHANNELS,
  PublicationTarget,
} from './curriculum/export.js';

export {
  ChatCompletionRequest,
  ChatCompletionResponse,
  ChatCompletionStreamEvent,
  ChatCompletionUsage,
  ChatMessage,
  ChatRole,
  DeidentificationProvenance,
  EmbeddingsRequest,
  EmbeddingsResponse,
  GatewayErrorBody,
  GatewayErrorCode,
  LogicalModel,
  ToolCall,
  ToolDefinition,
} from './gateway/chat.js';

export {
  ARTEFACT_TYPE_TO_AGENT,
  AccessibilityCheckItem,
  AccessibilityCheckResult,
  AccessibilityMode,
  ActivityStep,
  AnswerKeyEntry,
  AnswerKeyItem,
  AnswerKeyVerificationResult,
  ArtefactLinkage,
  AssessmentItem,
  AssessmentItemType,
  EnrichmentFocus,
  ExtensionSection,
  FORMAT_SUPPORT,
  GradeBand,
  MCOption,
  OfficialLanguage,
  PresentationPurpose,
  ReadabilityCheckInput,
  ReadabilityCheckResult,
  RemediationSection,
  RenderRequest,
  RenderResult,
  ResourceConstraint,
  Slide,
  TB01Input,
  TB01Result,
  TB02Input,
  TB02Result,
  TB03Input,
  TB03Result,
  TB04Input,
  TB04Result,
  TB05Input,
  TB05ItemInput,
  TB05Result,
  TB05VerificationItem,
  TB06Input,
  TB06Result,
  TB07Input,
  TB07Result,
  TB08Input,
  TB08Result,
  TB09Input,
  TB09Result,
  TB10Input,
  TB10Result,
  TB11Input,
  TB11Result,
  TBOutputLinkage,
  TeacherEditSignal,
  ToolboxArtefact,
  ToolboxArtefactType,
  ToolboxEditDiff,
  ToolboxEditField,
  ToolboxOutputFormat,
  VerifierAnswers,
  VisualBrief,
  WorksheetDifferentiationTier,
  WorksheetSection,
  dispatchRender,
} from './toolbox/index.js';

export {
  ArtefactEditRate,
  AssessmentItemSignal,
  AssessmentSignal,
  CoachingSession,
  CohortSuppressionResult,
  CoverageSignal,
  FlaggedItem,
  MINIMUM_COHORT_SIZE,
  MicroCourseModule,
  ObservationTheme,
  PD01Input,
  PD01Result,
  PD02CognitiveLevelCounts,
  PD02Input,
  PD02Result,
  PD03Input,
  PD03Result,
  PD04Input,
  PD04Result,
  PD05Input,
  PD05Result,
  PD06Input,
  PD06Result,
  PD07Input,
  PD07Result,
  PD08Input,
  PD08Result,
  PDNeedArea,
  PriorityGap,
  TeachingSignal,
  TopicDeliveryStatus,
  TopicGap,
  WalkthroughFocus,
  WalkthroughNote,
} from './mod-05/index.js';

export {
  AttributionMethod,
  COMMONS_K_ANONYMITY_THRESHOLD,
  CorrectionType,
  DecayReason,
  ExemplarCandidate,
  FieldCorrection,
  GatekeeperVerdict,
  HITLEventType,
  LabelledLearningEvent,
  LE01Input,
  LE01Result,
  LE02Input,
  LE02Result,
  LE03Input,
  LE03Result,
  LE04Input,
  LE04Result,
  LE05Input,
  LE05Result,
  LE06Input,
  LE06Result,
  LE07Input,
  LE07Result,
  LE08Input,
  LE08Result,
  LE09Input,
  LE09Result,
  MaturityLevel,
  MaturityReport,
  MinedPattern,
  PATTERN_MIN_SAMPLE_SIZE,
  PromotionLogEntry,
  PromptChallenger,
  PublishedPattern,
} from './learning/index.js';

export {
  CAPS_CODING_ROBOTICS_R3_DOC_ID,
  CAPS_CODING_ROBOTICS_R3_VERSION,
  CAPS_CR_R3_METADATA,
  CAPS_CR_R3_STRANDS,
  CodingRoboticsStrandId,
  EXPECTED_TERM_HOURS,
  StrandTermAllocation,
  type CapsCodingRoboticsR3Metadata,
} from './curriculum/sources/caps-coding-robotics-r3.js';

export {
  CAPS_IP_LIFE_SKILLS_GR46_DOC_ID,
  CAPS_IP_LIFE_SKILLS_GR46_METADATA,
  CAPS_IP_LIFE_SKILLS_GR46_STUDY_AREAS,
  CAPS_IP_LIFE_SKILLS_GR46_VERSION,
  EXPECTED_IP_LIFE_SKILLS_ANNUAL_HOURS,
  IPLifeSkillsStudyAreaId,
  StudyAreaAnnualAllocation,
  type CapsIPLifeSkillsGr46Metadata,
} from './curriculum/sources/caps-life-skills-ip-gr46.js';

export {
  CAPS_ISIZULU_FAL_GR13_DOC_ID,
  CAPS_ISIZULU_FAL_GR13_METADATA,
  CAPS_ISIZULU_FAL_GR13_SKILLS,
  CAPS_ISIZULU_FAL_GR13_VERSION,
  EXPECTED_FAL_WEEKLY_HOURS,
  FALSkillWeeklyAllocation,
  IsiZuluFALSkillId,
  type CapsIsiZuluFALGr13Metadata,
} from './curriculum/sources/caps-isizulu-fal-gr1-3.js';

export {
  CAPS_LIFE_SKILLS_R3_DOC_ID,
  CAPS_LIFE_SKILLS_R3_METADATA,
  CAPS_LIFE_SKILLS_R3_STUDY_AREAS,
  CAPS_LIFE_SKILLS_R3_VERSION,
  EXPECTED_LIFE_SKILLS_TERM_HOURS,
  LifeSkillsStudyAreaId,
  StudyAreaTermAllocation,
  type CapsLifeSkillsR3Metadata,
} from './curriculum/sources/caps-life-skills-r3.js';

export {
  CAPS_LO_SP_GR79_DOC_ID,
  CAPS_LO_SP_GR79_METADATA,
  CAPS_LO_SP_GR79_TOPICS,
  CAPS_LO_SP_GR79_VERSION,
  EXPECTED_LO_CONTACT_HOURS,
  LifeOrientationTopicId,
  TopicAnnualAllocation,
  type CapsLOSpGr79Metadata,
} from './curriculum/sources/caps-life-orientation-sp-gr79.js';

export const PACKAGE_NAME = '@infinite-ai/contracts' as const;
